### ISSUE TITLE
Get simple list of genes endpoint

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/civic-api-client#2]
Right now the api has a `/genes` endpoint that returns a subset of user-defined length with all genes and corresponding variants, variant groups, descriptions, etc. for those genes. It would be nice if this endpoint  instead returned a list of ALL genes in the database, limited only to the `id`, `name`, and `entrez_id` fields, so that one could use this as a quick reference for getting the appropriate CIViC identifiers for detailed queries (e.g. if I'm interested in BRAF I could use the returned result `{"id":5,"name":"BRAF","entrez_id":673}` to do a subsequent API call for BRAF at https://civic.genome.wustl.edu/api/genes/5)

**Comment by gatoravi** [comment]
Hi @ahwagner, this issue is for https://github.com/genome/civic-server perhaps? This would be super useful I agree.

**Comment by ahwagner** [comment]
I agree. Added this to https://github.com/genome/civic-server/issues/144.
