### ISSUE TITLE
Make this module respond more gracefully to a keyboard interrupt?

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-api-client#22]
Sometimes I choose the wrong options when running this tool and want to rerun it a different way.  When I do a <ctrl><c> I get a full traceback.  I assume it is possible to catch this and exit gracefully right?

Something like the first answer here perhaps:
http://stackoverflow.com/questions/21120947/catching-keyboardinterrupt-in-python-during-program-shutdown

**Comment by gatoravi** [comment]
This should be ok now.
