### ISSUE TITLE
add test that finds predictive evidence statements with no drug(s) defined

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-api-client#3]

**Comment by malachig** [comment]
Every evidence item of the `Evidence Type`: `Predictive` should have one or more drugs defined.  If not, display this evidence item record so that a curator can easily see a list of evidence items that need to be fixed.

**Comment by LeiChen0218** [comment]
Updated a new version in the same branch with modifications according to Malachi's suggestions.  You guys might want to take a look before merging.

**Comment by gatoravi** [comment]
This has been added in #11 Closing this issue.
