### ISSUE TITLE
add test to find variants where representative transcript ID is not of the form: ENST\d+\.\d+

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-api-client#6]
Each variant should have a representative transcript.  The ID for this transcript should have the following format: 

ENST00000355413.4

**Comment by malachig** [comment]
We should also check against a list of all valid ensembl transcripts for Ensembl v75. We can use an Ensembl GTF file for this purpose.  The correct one for the version of Ensembl we are currently using is here:

ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz

**Comment by LeiChen0218** [comment]
One question is that Homo_sapiens.GRCh37.75.gtf.gz only has transcript_id like ENST00000355413, the version information is not included. 
Shall we just check the part before "."?

**Comment by malachig** [comment]
This information is also available for each version of Ensembl:

ftp://ftp.ensembl.org/pub/release-75/mysql/homo_sapiens_core_75_37/transcript.txt.gz

On second thought it might be easier to just check transcript IDs against this file...

**Comment by LeiChen0218** [comment]
Ok. One more thing: do we require version information in each variant?
Because now the format checking codes would report things like ENST00000355413 as an error, but I guess people won’t always know which version it is…

**Comment by malachig** [comment]
There is always a version and it should be specified.  If it is missing we need to fix these cases.

**Comment by LeiChen0218** [comment]
got it.

On Feb 29, 2016, at 1:47 PM, Malachi Griffith <notifications@github.com<mailto:notifications@github.com>> wrote:

There is always a version and it should be specified. If it is missing we need to fix these cases.
